// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NatureAPi;

#nullable disable

namespace NatureAPi.Migrations
{
    [DbContext(typeof(NatureDBContext))]
    [Migration("20251022235945_SeedNuevasCONAmennn")]
    partial class SeedNuevasCONAmennn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryAPI.models.entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Amenity");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Name = "Miradores y pasarelas (Agua Azul)"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mirador panorámico (Divisadero)"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Refugio de alta montaña (Nevado)"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Muelle público y zona de nado (Bacalar)"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Embarcadero turístico (Sumidero)"
                        });
                });

            modelBuilder.Entity("LibraryAPI.models.entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Photo");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            PlaceId = 6,
                            URL = "https://visitachiapas.com/wp-content/uploads/32080021_2001255793535615_8694945979746484224_n-845x684.jpg"
                        },
                        new
                        {
                            Id = 7,
                            PlaceId = 7,
                            URL = "https://static.wixstatic.com/media/cf3297_1207992ee7504d6b89bef1ad615630e4~mv2.jpg/v1/fill/w_568,h_378,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/cf3297_1207992ee7504d6b89bef1ad615630e4~mv2.jpg"
                        },
                        new
                        {
                            Id = 8,
                            PlaceId = 8,
                            URL = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Vista_del_Nevado_de_Toluca.jpg/1280px-Vista_del_Nevado_de_Toluca.jpg"
                        },
                        new
                        {
                            Id = 9,
                            PlaceId = 9,
                            URL = "https://www.gob.mx/cms/uploads/article/main_image/83508/BACALAR-web.jpg"
                        },
                        new
                        {
                            Id = 10,
                            PlaceId = 10,
                            URL = "https://www.shutterstock.com/image-photo/sumidero-canyon-chiapas-mexico-600nw-2292202987.jpg"
                        });
                });

            modelBuilder.Entity("LibraryAPI.models.entities.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Accessible")
                        .HasColumnType("bit");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElevationMeters")
                        .HasColumnType("int");

                    b.Property<double>("EntryFee")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Place");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Accessible = true,
                            Category = "Cascada",
                            CreatedAt = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Conjunto de cascadas de color turquesa formadas por sales calcáreas en la selva chiapaneca; senderos, miradores y áreas de baño señalizadas.",
                            ElevationMeters = 150,
                            EntryFee = 50.0,
                            Latitude = 17.268000000000001,
                            Longitude = -92.108999999999995,
                            Name = "Cascadas de Agua Azul",
                            OpeningHours = "08:00 - 18:00"
                        },
                        new
                        {
                            Id = 7,
                            Accessible = true,
                            Category = "Cañón",
                            CreatedAt = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sistema de cañones más extenso que el Gran Cañón; miradores espectaculares, teleférico y rutas de senderismo en la Sierra Tarahumara.",
                            ElevationMeters = 2400,
                            EntryFee = 0.0,
                            Latitude = 27.535,
                            Longitude = -107.81,
                            Name = "Barrancas del Cobre (Divisadero)",
                            OpeningHours = "08:00 - 18:00"
                        },
                        new
                        {
                            Id = 8,
                            Accessible = true,
                            Category = "Volcán",
                            CreatedAt = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Volcán con lagunas crátericas (Sol y Luna) y paisajes de alta montaña; rutas de senderismo con control de acceso en temporada.",
                            ElevationMeters = 4680,
                            EntryFee = 54.0,
                            Latitude = 19.108000000000001,
                            Longitude = -99.757999999999996,
                            Name = "Nevado de Toluca (Xinantécatl)",
                            OpeningHours = "07:00 - 16:00"
                        },
                        new
                        {
                            Id = 9,
                            Accessible = true,
                            Category = "Laguna",
                            CreatedAt = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laguna cristalina de tonos azul-turquesa con estromatolitos, cenotes y balnearios; ideal para kayak, paddle y paseos en lancha.",
                            ElevationMeters = 10,
                            EntryFee = 50.0,
                            Latitude = 18.669,
                            Longitude = -88.391000000000005,
                            Name = "Laguna de Bacalar (Laguna de los Siete Colores)",
                            OpeningHours = "08:00 - 18:00"
                        },
                        new
                        {
                            Id = 10,
                            Accessible = true,
                            Category = "Cañón",
                            CreatedAt = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Imponente cañón con paredes de más de 1000 m de altura, recorridos en lancha por el río Grijalva y miradores panorámicos.",
                            ElevationMeters = 450,
                            EntryFee = 250.0,
                            Latitude = 16.832999999999998,
                            Longitude = -93.102000000000004,
                            Name = "Cañón del Sumidero",
                            OpeningHours = "08:00 - 17:00"
                        });
                });

            modelBuilder.Entity("LibraryAPI.models.entities.PlaceAmenity", b =>
                {
                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.HasKey("PlaceId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("PlaceAmenity");

                    b.HasData(
                        new
                        {
                            PlaceId = 6,
                            AmenityId = 5
                        },
                        new
                        {
                            PlaceId = 7,
                            AmenityId = 6
                        },
                        new
                        {
                            PlaceId = 8,
                            AmenityId = 7
                        },
                        new
                        {
                            PlaceId = 9,
                            AmenityId = 8
                        },
                        new
                        {
                            PlaceId = 10,
                            AmenityId = 9
                        },
                        new
                        {
                            PlaceId = 1,
                            AmenityId = 1
                        },
                        new
                        {
                            PlaceId = 1,
                            AmenityId = 2
                        },
                        new
                        {
                            PlaceId = 2,
                            AmenityId = 3
                        },
                        new
                        {
                            PlaceId = 2,
                            AmenityId = 4
                        });
                });

            modelBuilder.Entity("LibraryAPI.models.entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("LibraryAPI.models.entities.Trail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("EstimatedTimeMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsLoop")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Trail");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Difficulty = "Moderado",
                            DistanceKm = 2.3999999999999999,
                            EstimatedTimeMinutes = 75,
                            IsLoop = false,
                            Name = "Sendero Pozas Turquesa",
                            Path = "Tramo sombreado que sigue el cauce del rio con miradores a varias caidas; se avanza sobre pasarelas y roca humeda, con tramos resbalosos tras lluvia.",
                            PlaceId = 6
                        },
                        new
                        {
                            Id = 102,
                            Difficulty = "Dificil",
                            DistanceKm = 7.0,
                            EstimatedTimeMinutes = 210,
                            IsLoop = false,
                            Name = "Miradores del Divisadero",
                            Path = "Recorrido por la cresta con sube y baja constante; bordea varios miradores naturales con secciones expuestas y terreno pedregoso.",
                            PlaceId = 7
                        },
                        new
                        {
                            Id = 103,
                            Difficulty = "Dificil",
                            DistanceKm = 5.5,
                            EstimatedTimeMinutes = 180,
                            IsLoop = true,
                            Name = "Lagunas del Sol y la Luna",
                            Path = "Circuito a gran altitud que desciende al crater y rodea ambas lagunas; piso de arena volcanica y piedra suelta con pendientes pronunciadas.",
                            PlaceId = 8
                        },
                        new
                        {
                            Id = 104,
                            Difficulty = "Facil",
                            DistanceKm = 3.2000000000000002,
                            EstimatedTimeMinutes = 80,
                            IsLoop = true,
                            Name = "Costera de los Siete Colores",
                            Path = "Camino llano junto a la laguna con accesos a muelles y miradores; ideal para paseo suave con paradas para fotografias.",
                            PlaceId = 9
                        },
                        new
                        {
                            Id = 105,
                            Difficulty = "Moderado",
                            DistanceKm = 4.0,
                            EstimatedTimeMinutes = 120,
                            IsLoop = false,
                            Name = "Ribera del Grijalva",
                            Path = "Senda riberenia entre selva baja y paredones del cañon; zonas con lodazales en temporada y tramos estrechos junto al rio.",
                            PlaceId = 10
                        });
                });

            modelBuilder.Entity("LibraryAPI.models.entities.Photo", b =>
                {
                    b.HasOne("LibraryAPI.models.entities.Place", "Place")
                        .WithMany("Photos")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("LibraryAPI.models.entities.PlaceAmenity", b =>
                {
                    b.HasOne("LibraryAPI.models.entities.Amenity", "Amenity")
                        .WithMany("PlaceAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryAPI.models.entities.Place", "Place")
                        .WithMany("PlaceAmenities")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("LibraryAPI.models.entities.Review", b =>
                {
                    b.HasOne("LibraryAPI.models.entities.Place", "Place")
                        .WithMany("Reviews")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("LibraryAPI.models.entities.Trail", b =>
                {
                    b.HasOne("LibraryAPI.models.entities.Place", "Place")
                        .WithMany("Trails")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("LibraryAPI.models.entities.Amenity", b =>
                {
                    b.Navigation("PlaceAmenities");
                });

            modelBuilder.Entity("LibraryAPI.models.entities.Place", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("PlaceAmenities");

                    b.Navigation("Reviews");

                    b.Navigation("Trails");
                });
#pragma warning restore 612, 618
        }
    }
}
